config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "main#index"
  post "/", to: "sessions#create"

  resources :users, only:[:show, :new, :create]
  resources :registries, only: [:show, :update, :new, :create] do
    resources :participants, only: [:new, :create]
    resources :user_registries, only: [:new, :create, :destroy]
  end
  resources :participants, only: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord
  # Validations
  validates_presence_of :name
  validates_uniqueness_of :name

  validates_presence_of :gender
  validates_presence_of :birthday
  validates_presence_of :contact_method
  validates_presence_of :email
  validates_presence_of :phone

  # Associations
  has_many :participant_registries, dependent: :destroy
  has_many :registries, through: :participant_registries
  belongs_to :user

  # Enums
  enum contact_method: {Phone: 0, Email: 1}

  def self.count_by_birth_year
    ans = Participant.group("DATE_TRUNC('year', birthday)").count
    new_hash = {}
    ans.map do |year, count|
      new_year = year.to_date.year
      new_hash[new_year] = count
    end
    new_hash
  end
end

app/models/participant_registry.rb
class ParticipantRegistry < ApplicationRecord
  # Validations
  validates_uniqueness_of :participant_id, scope: :registry_id

  # Relationships 
  belongs_to :participant
  belongs_to :registry

end

app/models/registry.rb
class Registry < ApplicationRecord
  # Validations
  validates_presence_of :name
  validates_uniqueness_of :name

  validates_presence_of :location

  # Associations
  has_many :user_registries
  has_many :users, through: :user_registries
  has_many :participant_registries
  has_many :participants, through: :participant_registries
end

app/models/user.rb
class User < ApplicationRecord
  # Validations
  validates_presence_of :email
  validates_uniqueness_of :email

  validates_presence_of :phone
  validates_uniqueness_of :phone
  
  validates_presence_of :name
  validates_uniqueness_of :name

  # Associations
  has_many :user_registries
  has_many :registries, through: :user_registries
  has_many :participants

  def find_enrolled(registry)
    #fixme - better to have a GROUP BY in the controller
    registry.participants.select("participants.*, participant_registries.created_at AS enrolled_at").where(user: self)
  end
end

app/models/user_registry.rb
class UserRegistry < ApplicationRecord
  belongs_to :user
  belongs_to :registry
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
  
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def show
  end

  def new 
    @registry = Registry.find(params[:registry_id])
    @participant = @registry.participants.build
  end

  def create
    #FIXME - refactor later 
    if params[:registry_id]
      @registry = Registry.find(params[:registry_id])
      @participant = @registry.participants.create(participant_params)
    end
    if params[:registry_id] && @participant.save
      redirect_to registry_path(@registry)
    else
      flash[:errors] = @participant.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    if registry = Registry.find(params[:registry_id])
      Participant.destroy(params[:id])
      redirect_to registry_path(registry)
    end
  end

  private

  def participant_params
    user_info = {user_id: current_user.id}
    params.require(:participant).permit(:name, :gender, :birthday, :contact_method, :email, :phone, :notes).merge(user_info)
  end

end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  def show
    @registry = Registry.find(params[:id])
    @users = @registry.users
  end
  
  def update
    if params[:toggle]
      registry = Registry.find(params[:id])
      registry.toggle(:open).save
      redirect_to registry_path(registry)
    end
  end

  def new
    @registry = Registry.new
  end

  def create
    registry = Registry.new(registry_params)
    
    if registry.save
      UserRegistry.create(registry: registry, user: current_user)
      redirect_to user_path(current_user)
    else
      flash[:errors] = registry.errors.full_messages.to_sentence
      render :new
    end
  end

  private 

  def registry_params
    params.require(:registry).permit(:name, :location)
  end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:user][:email])
    session[:user_id] = user.id
    redirect_to user_path(user)
  end
end

app/controllers/user_registries_controller.rb
class UserRegistriesController < ApplicationController
  def new
    @registry = Registry.find(params[:registry_id])
    @users = User.all
  end

  def create
    registry = Registry.find(params[:registry_id])
    user = User.find_by(email: params[:email])
    registry.user_registries.create(user: user)
    redirect_to registry_path(registry)
  end

  def destroy
    registry = Registry.find(params[:registry_id])
    user = User.find(params[:user_id])
    user_registry = UserRegistry.find_by(user: user, registry: registry)
    user.user_registries.delete(user_registry)
    redirect_to registry_path(registry)
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_registries = current_user.registries
    @count_by_birth_year = Participant.count_by_birth_year
  end

  def new
    @user = User.new
  end
  
  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  private 

  def user_params
    params.require(:user).permit(:name, :email, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Registrar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <ul>
        <% if current_user %>
          <li><%= link_to 'Dashboard', user_path(current_user) %></li>
        <% end %>
        <%# <li><%= link_to 'Registries', registries_path </li> %>
      </ul>
    </nav>
    <% if flash[:errors] %>
        <p><%= flash[:errors] if flash[:errors]%></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<main>
  <h1>"Welcome to Registrar!"</h1>
  
  <section id="login">
    <%= link_to 'Register', new_user_path %>
    <%= form_for :user do |f| %>
      <%= f.label :email, "Enter Email" %>
      <%= f.text_field :email %>
      <%= f.submit "Login" %>
    <% end %>
  </section>
</main>

app/views/participants/new.html.erb
<h1>Add a Participant</h1>

<%= form_for [@registry, @participant] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :gender %>
  <%# taken from Human rights campaign ('hrc.org') %>
  <%= f.select(:gender, [['Female','Female'], ['Male', 'Male'], ['Non-Binary/3rd Gender', 'Non-Binary/3rd Gender']]) %>
  <%= f.label :birthday %>
  <%= f.date_field :birthday %>
  <%= f.label :contact_method %>
  <%= f.select(:contact_method, [['Phone', 'Phone'], ['Email', 'Email']]) %>
  <%= f.label :email, "Email Address" %>
  <%= f.text_field :email %>
  <%= f.label :phone, "Phone Number"%>
  <%= f.text_field :phone %>
  <%= f.label :notes %>
  <%= f.text_area :notes %>

  <%= f.submit "Submit"%>
<% end %>

app/views/participants/show.html.erb
hello world

app/views/registries/new.html.erb
<%= form_for @registry do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.submit "Submit" %>
<% end %>

app/views/registries/show.html.erb
<section id="basic-info">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <td><%= @registry.name %></td>
      <td><%= @registry.location %></td>
      <% if @registry.open %>
        <td> Open </td>
      <% else %>
        <td> Closed </td>
      <% end %>
      <td><%= link_to "Toggle Open Status", registry_path(@registry, toggle: true), method: :patch %></td>
    </tbody>
  </table>
</section>

<section id="users">
  <h2>Coordinators</h2>
  <%= link_to 'Add Coordinator', new_registry_user_registry_path(@registry) %>
  <% @users.each do |user| %>
    <table>
      <thead>
        <tr>
          <td>Name</td>
          <td>Phone</td>
          <td>Email</td>
        </tr>
      </thead>
      <tbody>
          <tr id=<%= "user-#{user.id}" %>>
            <td><%= user.name %></td>
            <td><%= user.phone %></td>
            <td><%= user.email %></td>
            <td><%= link_to "Remove Coordinator", registry_user_registry_path(@registry, user_id: user.id), method: :delete %></td>
          </tr>
      </tbody>
    </table>
    <section id="participants">
      <%= link_to "Add Participant", new_registry_participant_path(@registry) %>
      <table>
        <thead>
        <t>
            <td>Name</td>
            <td>Gender</td>
            <td>Birthday</td>
            <td>Contact Method</td>
            <td>Email</td>
            <td>Phone</td>
        </tr>
        </thead>
        <tbody>
          <% user.find_enrolled(@registry).each do |participant| %>
            <tr id=<%= "participant-#{participant.id}" %>>
              <td><%= link_to participant.name, participant_path(participant) %></td>
              <td><%= participant.gender %></td>
              <td><%= participant.birthday %></td>
              <td><%= participant.contact_method %></td>
              <td><%= participant.email %></td>
              <td><%= participant.phone %></td>
              <td><%= participant.enrolled_at.to_date %></td>
              <td><%= link_to "Remove Participant", participant_path(participant, registry_id: @registry.id), method: :delete, data: {confirm: "Are you sure?"} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
  <% end %>
</section>

app/views/user_registries/new.html.erb
  <table>
    <thead>
      <tr>
        <td>Name</td>
        <td>Phone</td>
        <td>Email</td>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, registry_user_registries_path(@registry, email: user.email), method: :post %></td>
          <td><%= user.phone %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/new.html.erb
<h1>Register Here!</h1>

<section id="register">
  <%= form_for @user do |f| %>
    <%= f.label :name, "Name (first & last)"%>
    <%= f.text_field :name%>
    <%= f.label :email%>
    <%= f.text_field :email%>
    <%= f.label :phone%>
    <%= f.text_field :phone%>
    <%= f.submit "Submit" %>
  <% end %>
</section>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.name %></h1>

<section id="user-info">
  <p>Basic Info</p>
  <table>
    <tr>
      <th>Phone Number</th>
      <th>Email Address</th>
    </tr>

    <tr>
      <td><%= current_user.phone %></td>
      <td><%= current_user.email %></td>
    </tr>
  </table>
</section>

<section>
  <h3><%= "Your Registries" %></h3>
  <%= link_to 'Create Registry', new_registry_path %>

  <table id="user-registries">
    <tr>
      <th>Name</th>
      <th>Location</th>
    </tr>

    <% @user_registries.each do |registry| %>
      <tr>
        <th><%= link_to registry.name, registry_path(registry) %></th>
        <th><%= registry.location %></th>
      </tr>
    <% end %>

  </table>
</section>

<section>
  <h3>Business Logic</h3>

  <h4>Count of participants by Birth Year</h4>
  <% @count_by_birth_year.each do |year, count| %>
    <p><%= "#{year} - #{count}" %></p>
  <% end %>
</section>